services:
  app:
    build: .
    container_name: sportline_app
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: example
      DB_NAME: sportlinedb
      JWT_ACCESS_SECRET: your-super-secret-access-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      RUN_SEEDER: "true"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    image: postgres:16
    container_name: sportline_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sportlinedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sportlinedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  pgdata:

networks:
  app-network:
